server:
  servlet:
    context-path: /api
  port: 8081

spring:
  application:
    name: customer
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_customer
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/eazybankdev/protocol/openid-connect/certs

logging:
  level:
    web: debug

