server:
  #  servlet:
  #    context-path: /api
  port: 8080

spring:
  application:
    name: customer
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_customer?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true

springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    web: debug